services:
  - name: stock-fight-backend
    type: web
    env: docker
    plan: free
    buildCommand: docker build -t stock-fight-backend .
    startCommand: docker run -p 8000:8000 stock-fight-backend
    envVars:
      - key: FINNHUB_API_KEY
        value: YOUR_FINNHUB_API_KEY
      - key: ALPHA_VANTAGE_API_KEY
        value: YOUR_ALPHA_VANTAGE_API_KEY
      - key: REDIS_URL
        value: YOUR_REDIS_URL
  - name: stock-fight-frontend
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm run serve
    envVars:
      - key: VITE_API_URL
        value: "https://stock-fight-backend.onrender.com"
