services:
  - name: stock-fight-backend
    type: web
    env: python
    plan: free
    buildCommand: 
      - pip install poetry
      - poetry env use 3.12
      - poetry install
    startCommand: poetry run uvicorn stock_fight.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FINNHUB_API_KEY
        value: YOUR_FINNHUB_API_KEY
      - key: ALPHA_VANTAGE_API_KEY
        value: YOUR_ALPHA_VANTAGE_API_KEY
      - key: REDIS_URL
        fromDatabase:
          name: your-redis-instance-name
          property: connectionString
  - name: stock-fight-frontend
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm run serve
    envVars:
      - key: VITE_API_URL
        value: "https://stock-fight-backend.onrender.com"
